;;; color-theme-me.el --- 

;; Copyright 2012 yao
;;
;; Author: yao@Shengzhes-MacBook-Pro.local
;; Version: $Id: color-theme-me.el,v 0.0 2012/04/10 07:03:00 yao Exp $
;; Keywords: 
;; X-URL: not distributed yet

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program; if not, write to the Free Software
;; Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

;;; Commentary:

;; 

;; Put this file into your load-path and the following into your ~/.emacs:
;;   (require 'color-theme-me)

;;; Code:
(defun color-theme-me ()

  (interactive)
  (color-theme-install
   '(color-theme-me nil nil
     (zmacs-region ((t (:background "blue3"))))
     (zencoding-preview-output ((t (:background "darkolivegreen"))))
     (zencoding-preview-input ((t (:background "SkyBlue4" :box 1))))
     (yas/field-highlight-face ((t (:background "blue3"))))
     (yas/field-debug-face ((t (nil))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "light gray"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-button ((t (:bold t :weight bold))))
     (vertical-border ((t (nil))))
     (variable-pitch ((t (:family "helv"))))
     (underline ((t (:underline t))))
     (trailing-whitespace ((t (:background "red"))))
     (tooltip ((t (:family "helv" :background "lightyellow" :foreground "black"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (text-cursor ((t (:background "aa0000" :foreground "black"))))
     (template-message-face ((t (:bold t :weight bold))))
     (tabbar-unselected ((t (:foreground "grey75" :background "gray50" :family "helv" :box (:line-width 1 :color "white" :style released-button) :height 0.8))))
     (tabbar-separator ((t (:foreground "grey75" :background "gray50" :family "helv" :height 0.08000000000000002))))
     (tabbar-selected ((t (:background "gray50" :family "helv" :foreground "blue" :box (:line-width 1 :color "white" :style pressed-button) :height 0.8))))
     (tabbar-highlight ((t (:underline t))))
     (tabbar-default ((t (:family "helv" :background "gray50" :foreground "grey75" :height 0.8))))
     (tabbar-button-highlight ((t (:foreground "grey75" :background "gray50" :family "helv" :height 0.8))))
     (tabbar-button ((t (:foreground "grey75" :background "gray50" :family "helv" :box (:line-width 1 :color "white" :style released-button) :height 0.8))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-directory-face ((t (:foreground "light blue"))))
     (speedbar-button-face ((t (:foreground "green3"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (show-paren-match ((t (:background "steelblue3"))))
     (shadow ((t (:foreground "grey70"))))
     (senator-read-only-face ((t (:background "#664444"))))
     (senator-momentary-highlight-face ((t (:background "gray30"))))
     (senator-intangible-face ((t (:foreground "gray75"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (semantic-dirty-token-face ((t (:background "lightyellow"))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (scroll-bar ((t (nil))))
     (region ((t (:background "blue3"))))
     (query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
     (primary-selection ((t (:background "blue3"))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-menu-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "sky blue"))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (ns-working-text-face ((t (:underline t))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (next-error ((t (:background "blue3"))))
     (mouse ((t (:background "black"))))
     (mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (menu ((t (nil))))
     (match ((t (:background "RoyalBlue3"))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (left-margin ((t (nil))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-package-face ((t (:foreground "steelblue1"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-number-face ((t (:foreground "LightSalmon"))))
     (jde-java-font-lock-modifier-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-link-face ((t (:foreground "cadetblue" :underline t :slant normal))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "light coral"))))
     (jde-java-font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-api-face ((t (:foreground "light goldenrod"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (italic ((t (:italic t :slant italic))))
     (isearch-fail ((t (:background "red4"))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (ido-subdir ((t (:bold t :foreground "#D61619" :weight bold))))
     (ido-only-match ((t (:bold t :foreground "#007B22" :weight bold))))
     (ido-first-match ((t (:bold t :foreground "#007B22" :weight bold))))
     (highline-face ((t (:background "#426BEE"))))
     (highlight ((t (:background "darkolivegreen"))))
     (help-argument-name ((t (:italic t :slant italic))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey20" :foreground "grey90" :box nil))))
     (gui-element ((t (:background "#aa0000" :foreground "#00aa00"))))
     (fringe ((t (:background "grey10"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
     (font-lock-variable-name-face ((t (:foreground "gold"))))
     (font-lock-type-face ((t (:foreground "yellow" :height 1.05))))
     (font-lock-string-face ((t (:foreground "LightSalmon"))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "#00BD41"))))
     (font-lock-reference-face ((t (:foreground "#7175F0"))))
     (font-lock-preprocessor-face ((t (:foreground "#f78219"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-keyword-face ((t (:bold t :foreground "LightPink" :weight bold :height 1.05))))
     (font-lock-function-name-face ((t (:bold t :foreground "DodgerBlue" :weight bold :height 1.05))))
     (font-lock-doc-string-face ((t (:foreground "#3C403B"))))
     (font-lock-doc-face ((t (:foreground "LightSalmon"))))
     (font-lock-constant-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (font-lock-comment-face ((t (:italic t :foreground "lightgreen" :slant oblique))))
     (font-lock-comment-delimiter-face ((t (:foreground "#3C403B"))))
     (font-lock-builtin-face ((t (:bold t :foreground "LightSkyBlue" :underline t :weight bold))))
     (fixed-pitch ((t (:family "courier"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fg:erc-color-face9 ((t (:foreground "green"))))
     (fg:erc-color-face8 ((t (:foreground "yellow"))))
     (fg:erc-color-face7 ((t (:foreground "orange"))))
     (fg:erc-color-face6 ((t (:foreground "purple"))))
     (fg:erc-color-face5 ((t (:foreground "brown"))))
     (fg:erc-color-face4 ((t (:foreground "red"))))
     (fg:erc-color-face3 ((t (:foreground "green4"))))
     (fg:erc-color-face2 ((t (:foreground "blue4"))))
     (fg:erc-color-face15 ((t (:foreground "gray90"))))
     (fg:erc-color-face14 ((t (:foreground "gray50"))))
     (fg:erc-color-face13 ((t (:foreground "deeppink"))))
     (fg:erc-color-face12 ((t (:foreground "blue"))))
     (fg:erc-color-face11 ((t (:foreground "cyan"))))
     (fg:erc-color-face10 ((t (:foreground "lightblue1"))))
     (fg:erc-color-face1 ((t (:foreground "black"))))
     (fg:erc-color-face0 ((t (:foreground "White"))))
     (eshell-ls-unreadable-face ((t (:foreground "DarkGrey"))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "Cyan" :weight bold))))
     (eshell-ls-special-face ((t (:bold t :foreground "Magenta" :weight bold))))
     (eshell-ls-readonly-face ((t (:foreground "Pink"))))
     (eshell-ls-product-face ((t (:foreground "LightSalmon"))))
     (eshell-ls-missing-face ((t (:bold t :foreground "Red" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "Green" :weight bold))))
     (eshell-ls-directory-face ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "LightSalmon"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "Orchid" :weight bold))))
     (escape-glyph ((t (:foreground "cyan"))))
     (erc-underline-face ((t (:underline t))))
     (erc-timestamp-face ((t (:bold t :foreground "green" :weight bold))))
     (erc-prompt-face ((t (:bold t :background "lightBlue2" :foreground "Black" :weight bold))))
     (erc-notice-face ((t (:bold t :foreground "SlateBlue" :weight bold))))
     (erc-inverse-face ((t (:background "Black" :foreground "White"))))
     (erc-input-face ((t (:foreground "brown"))))
     (erc-error-face ((t (:background "Red" :foreground "White"))))
     (erc-direct-msg-face ((t (:foreground "IndianRed"))))
     (erc-default-face ((t (nil))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-action-face ((t (:bold t :weight bold))))
     (dropdown-list-selection-face ((t (:foreground "black" :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "apple" :family "Bitstream_Vera_Sans_Mono" :background "purple" :height 140))))
     (dropdown-list-face ((t (:family "Bitstream_Vera_Sans_Mono" :foundry "apple" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "lightyellow" :foreground "black" :height 140))))
     (custom-variable-tag-face ((t (:bold t :foreground "light blue" :weight bold :height 1.2 :family "helv"))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-state-face ((t (:foreground "lime green"))))
     (custom-set-face ((t (:background "white" :foreground "blue"))))
     (custom-saved-face ((t (:underline t))))
     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
     (custom-modified-face ((t (:background "blue" :foreground "white"))))
     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
     (custom-group-tag-face-1 ((t (:bold t :foreground "pink" :weight bold :height 1.2 :family "helv"))))
     (custom-group-tag-face ((t (:bold t :foreground "light blue" :weight bold :height 1.2))))
     (custom-face-tag-face ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (custom-documentation-face ((t (nil))))
     (custom-comment-tag-face ((t (:foreground "gray80"))))
     (custom-comment-face ((t (:background "dim gray"))))
     (custom-changed-face ((t (:background "blue" :foreground "white"))))
     (custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (cursor ((t (:background "black"))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (completions-common-part ((t (:family "Bitstream_Vera_Sans_Mono" :foundry "apple" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "gainsboro" :background "grey30" :stipple nil :height 140))))
     (completions-annotations ((t (:italic t :slant italic))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (border-glyph ((t (nil))))
     (border ((t (:background "black"))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bold ((t (:bold t :weight bold))))
     (bg:erc-color-face9 ((t (:background "green"))))
     (bg:erc-color-face8 ((t (:background "yellow"))))
     (bg:erc-color-face7 ((t (:background "orange"))))
     (bg:erc-color-face6 ((t (:background "purple"))))
     (bg:erc-color-face5 ((t (:background "brown"))))
     (bg:erc-color-face4 ((t (:background "red"))))
     (bg:erc-color-face3 ((t (:background "green4"))))
     (bg:erc-color-face2 ((t (:background "blue4"))))
     (bg:erc-color-face15 ((t (:background "gray90"))))
     (bg:erc-color-face14 ((t (:background "gray50"))))
     (bg:erc-color-face13 ((t (:background "deeppink"))))
     (bg:erc-color-face12 ((t (:background "blue"))))
     (bg:erc-color-face11 ((t (:background "cyan"))))
     (bg:erc-color-face10 ((t (:background "lightblue1"))))
     (bg:erc-color-face1 ((t (:background "black"))))
     (bg:erc-color-face0 ((t (:background "White"))))
     (ac-yasnippet-selection-face ((t (:background "coral3" :foreground "white"))))
     (ac-yasnippet-candidate-face ((t (:background "sandybrown" :foreground "black"))))
     (ac-selection-face ((t (:background "steelblue" :foreground "white"))))
     (ac-gtags-selection-face ((t (:background "navy" :foreground "white"))))
     (ac-gtags-candidate-face ((t (:background "lightgray" :foreground "navy"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-candidate-face ((t (:background "lightgray" :foreground "black" :underline "darkgray"))))
     (default ((t (:stipple nil :background "#191919" :foreground "#929292" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "apple" :family "Bitstream_Vera_Sans_Mono")))))))

(provide 'color-theme-me)
(eval-when-compile
  (require 'cl))



;;;;##########################################################################
;;;;  User Options, Variables
;;;;##########################################################################





;;; color-theme-me.el ends here
